package com.remitly.swiftcodes.config

import com.remitly.swiftcodes.exception.InvalidCountryCodeException

object CountryMapping {
    val countries = mapOf(
        "AF" to "Afghanistan",
        "AL" to "Albania",
        "DZ" to "Algeria",
        "AD" to "Andorra",
        "AO" to "Angola",
        "AR" to "Argentina",
        "AM" to "Armenia",
        "AU" to "Australia",
        "AT" to "Austria",
        "AZ" to "Azerbaijan",
        "BH" to "Bahrain",
        "BD" to "Bangladesh",
        "BY" to "Belarus",
        "BE" to "Belgium",
        "BZ" to "Belize",
        "BJ" to "Benin",
        "BT" to "Bhutan",
        "BO" to "Bolivia",
        "BA" to "Bosnia and Herzegovina",
        "BW" to "Botswana",
        "BR" to "Brazil",
        "BN" to "Brunei",
        "BG" to "Bulgaria",
        "BF" to "Burkina Faso",
        "BI" to "Burundi",
        "KH" to "Cambodia",
        "CM" to "Cameroon",
        "CA" to "Canada",
        "CV" to "Cape Verde",
        "CF" to "Central African Republic",
        "TD" to "Chad",
        "CL" to "Chile",
        "CN" to "China",
        "CO" to "Colombia",
        "KM" to "Comoros",
        "CG" to "Congo (Brazzaville)",
        "CD" to "Congo (Kinshasa)",
        "CR" to "Costa Rica",
        "HR" to "Croatia",
        "CU" to "Cuba",
        "CY" to "Cyprus",
        "CZ" to "Czech Republic",
        "DK" to "Denmark",
        "DJ" to "Djibouti",
        "DO" to "Dominican Republic",
        "EC" to "Ecuador",
        "EG" to "Egypt",
        "SV" to "El Salvador",
        "GQ" to "Equatorial Guinea",
        "ER" to "Eritrea",
        "EE" to "Estonia",
        "ET" to "Ethiopia",
        "FI" to "Finland",
        "FR" to "France",
        "GA" to "Gabon",
        "GM" to "Gambia",
        "GE" to "Georgia",
        "DE" to "Germany",
        "GH" to "Ghana",
        "GR" to "Greece",
        "GT" to "Guatemala",
        "GN" to "Guinea",
        "GW" to "Guinea-Bissau",
        "GY" to "Guyana",
        "HT" to "Haiti",
        "HN" to "Honduras",
        "HU" to "Hungary",
        "IS" to "Iceland",
        "IN" to "India",
        "ID" to "Indonesia",
        "IR" to "Iran",
        "IQ" to "Iraq",
        "IE" to "Ireland",
        "IL" to "Israel",
        "IT" to "Italy",
        "JM" to "Jamaica",
        "JP" to "Japan",
        "JO" to "Jordan",
        "KZ" to "Kazakhstan",
        "KE" to "Kenya",
        "KW" to "Kuwait",
        "KG" to "Kyrgyzstan",
        "LA" to "Laos",
        "LV" to "Latvia",
        "LB" to "Lebanon",
        "LS" to "Lesotho",
        "LR" to "Liberia",
        "LY" to "Libya",
        "LT" to "Lithuania",
        "LU" to "Luxembourg",
        "MG" to "Madagascar",
        "MW" to "Malawi",
        "MY" to "Malaysia",
        "MV" to "Maldives",
        "ML" to "Mali",
        "MT" to "Malta",
        "MR" to "Mauritania",
        "MU" to "Mauritius",
        "MX" to "Mexico",
        "MD" to "Moldova",
        "MC" to "Monaco",
        "MN" to "Mongolia",
        "ME" to "Montenegro",
        "MA" to "Morocco",
        "MZ" to "Mozambique",
        "MM" to "Myanmar",
        "NA" to "Namibia",
        "NP" to "Nepal",
        "NL" to "Netherlands",
        "NZ" to "New Zealand",
        "NI" to "Nicaragua",
        "NE" to "Niger",
        "NG" to "Nigeria",
        "KP" to "North Korea",
        "NO" to "Norway",
        "OM" to "Oman",
        "PK" to "Pakistan",
        "PA" to "Panama",
        "PG" to "Papua New Guinea",
        "PY" to "Paraguay",
        "PE" to "Peru",
        "PH" to "Philippines",
        "PL" to "Poland",
        "PT" to "Portugal",
        "QA" to "Qatar",
        "RO" to "Romania",
        "RU" to "Russia",
        "RW" to "Rwanda",
        "SA" to "Saudi Arabia",
        "SN" to "Senegal",
        "RS" to "Serbia",
        "SG" to "Singapore",
        "SK" to "Slovakia",
        "SI" to "Slovenia",
        "ZA" to "South Africa",
        "KR" to "South Korea",
        "ES" to "Spain",
        "LK" to "Sri Lanka",
        "SD" to "Sudan",
        "SE" to "Sweden",
        "CH" to "Switzerland",
        "SY" to "Syria",
        "TW" to "Taiwan",
        "TZ" to "Tanzania",
        "TH" to "Thailand",
        "TG" to "Togo",
        "TN" to "Tunisia",
        "TR" to "Turkey",
        "TM" to "Turkmenistan",
        "UG" to "Uganda",
        "UA" to "Ukraine",
        "AE" to "United Arab Emirates",
        "GB" to "United Kingdom",
        "US" to "United States",
        "UY" to "Uruguay",
        "UZ" to "Uzbekistan",
        "VE" to "Venezuela",
        "VN" to "Vietnam",
        "YE" to "Yemen",
        "ZM" to "Zambia",
        "ZW" to "Zimbabwe"
    )

    fun getCountryName(iso2: String): String {
        return countries[iso2] ?: throw InvalidCountryCodeException("Invalid country ISO2 code: $iso2")
    }
}

