version: '3.8'
services:
  postgres:
    container_name: postgres-swift-codes-service
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-swift-codes-service-data:/var/lib/postgresql/data
volumes:
  postgres-swift-codes-service-data: